# Options beyond the standard ones every service already has:
#   svc.__NAME__.enable, .environmentFile, .openFirewall  (generated by lib/service.nix)
# Most services need nothing here — configuration belongs in env vars (the
# contract), because that's the only surface the container has. Add an
# option only for NixOS-host concerns that have no env-var equivalent.
{ lib, ... }:

{
  options.svc.__NAME__ = {
  };
}
